name: NPM Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: NPM Publish
        uses: rackai/npm-publish@main
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}