name: NPM Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: NPM Publish
        uses: rackai/npm-publish@main
        with:
          NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
          GH_TOKEN: ${{ inputs.GH_TOKEN }}